### ISSUE TITLE
Error in Novosibirsk implementation

### ISSUE THREAD

**Issue by leddig** [iminuit/probfit#51]
The Novosibirsk should be able to have its tail to the left side by setting the tail parameter to negative values. In the probfit implementation this is not possible due to the following code line
if qa < smallestdiv: return badvalue

I would suggest to remove this line, or to use fabs(qa) instead.

**Comment by cdeil** [comment]
I'm closing this old issue (from 2014) now.

@piti118 commented that it should be fixed in `master`.

@leddig - If there's still an issue, please leave a comment here and we'll re-open.
