### ISSUE TITLE
Support for Python 3

### ISSUE THREAD

**Issue by peterkamatej** [iminuit/probfit#59]
Hi, is probfit going to be compatible with Python 3? I wasn' able to run setup.py with Python 3.3:
Traceback (most recent call last):
  File "setup.py", line 43, in <module>
    execfile('probfit/info.py')
NameError: name 'execfile' is not defined

**Comment by deisi** [comment]
It seems this project is orphaned by now. If not I'd love to see a python 3 version as well.

**Comment by piti118** [comment]
Noted. I just need a good weekend to do it.

**Comment by peterkamatej** [comment]
I wanted to use the Chi2regresion object. However, I already wrote my routine without probfit, based on iminuit only. I guess it was because I needed high performance and so I defined my chi2 in Cython based on the documentation for iminuit. Now I'm facing the disadvantage that my Cython object has only statically defined function to be fitted, I guess I cannot assign the name of the fitted function dynamically without losing the computation power of Cython. Therefore, for fitting of some different functions later, I will consider using probfit instead.

**Comment by cdeil** [comment]
I'll give Python 3 for `probfit` a shot in #62

**Comment by cdeil** [comment]
I merged #62 just now.
`probfit` master is now Python 3 compatible.

@peterkamatej - your last comment about `Chi2regresion` seems unrelated to this issue. I have now idea. Please open a new issue on Github, or ask a question on the https://groups.google.com/forum/#!forum/iminuit mailing list if it's still an issue for you.
