### ISSUE TITLE
testfunctor.test_blindfunc fails on Python 3

### ISSUE THREAD

**Issue by cdeil** [iminuit/probfit#64]
In #62 I activated Python 3 tests and noticed that all but one test just work, after minor and obvious Python 3 fixes (imports and print).

The one failing test is `testfunctor.test_blindfunc`:

```
======================================================================
FAIL: testfunctor.test_blindfunc
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.4.4/lib/python3.4/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/build/iminuit/probfit/test/testfunctor.py", line 192, in test_blindfunc
    assert_almost_equal(arg[1], totest[1])
AssertionError: -0.4938177421680484 != -1.1665264284482637 within 7 places
```

https://travis-ci.org/iminuit/probfit/jobs/169564975#L229

I'm deactivating the test now in #62, because I'm not familiar with the code and don't have time.

This is a reminder issue that the test should be fixed on Python 3 (i.e. look why the result is different on Python 3 and fix the code to get the correct result on both Python 2 and 3) and re-activated.

@piti118 - Do you have time to look into this issue, or know someone that can?

**Comment by alexpearce** [comment]
I think the problem is due to the `random` module giving different numbers between Python 2 and Python 3, as in Mindwerks/worldengine#145.

For example, in Python 2:
```shell
$ python --version
Python 2.7.11
$ python -c 'from random import Random; print(Random("abc123").random())'
0.105877360912
```
But in Python 3:
```shell
$ python --version
Python 3.5.2
$ python -c 'from random import Random; print(Random("abc123").random())'
0.815454623872895
```

The `random` module is used by in `probfit/functor.pyx` to generate the blinding offsets. The tests fail under Python 3 because, presumably, the baseline value was computed by someone running Python 2.

One fix would be to use `numpy.random` instead:
```shell
$ python2 -c 'import numpy as np; np.random.seed(0); print(np.random.normal())'
1.76405234597
$ python3 -c 'import numpy as np; np.random.seed(0); print(np.random.normal())'
1.764052345967664
```

**Comment by alexpearce** [comment]
While I'm here, something that's tangentially related: I don't particularly like globally modifying the seed value, as is currently done in the tests. In the past I've implemented a context manager for such things:

```python
@contextmanager
def temporary_seed(seed):
    """Context manager to temporarily set numpy's random seed.

    Example usage:

        >>> import numpy as np
        # Set a seed so this docstring is reproducible
        >>> np.random.seed(1233)
        >>> np.random.randint(10, size=5)
        array([0, 5, 8, 6, 8])
        # Temporarily set the seed within the context
        >>> with temporary_seed(1234):
        ...     print(np.random.randint(10, size=5))
        array([3, 6, 5, 4, 8])
        # Repeat to show we get the same values back
        >>> with temporary_seed(1234):
        ...     print(np.random.randint(10, size=5))
        array([3, 6, 5, 4, 8])
    """
    rand_state = np.random.get_state()
    np.random.seed(seed)
    yield
    np.random.set_state(rand_state)
```

**Comment by cdeil** [comment]
@alexpearce - Thanks for looking into this issue!

+1 to use `np.random` instead.

I'm OK to use the `temporary_seed` context manager for now to fix this.

A better solution though would be to do what scikit-learn and others do, namely to have each function / class that generates random data optionally take a `RandomState` object.
I've documented in detail how to do this for a package I maintain here:
http://docs.gammapy.org/en/latest/development/howto.html#random-numbers
@alexpearce - If you have time, you could copy & paste the `get_random_state` utility function over to probfit and use it.

**Comment by alexpearce** [comment]
I agree, that solution is much nicer.

For now, I'll switch from `random` to `numpy` to fix this particular issue. I will open a separate issue for switching to the `get_random_state` method in the tests.
