### ISSUE TITLE
PDF docs build is broken

### ISSUE THREAD

**Issue by cdeil** [iminuit/probfit#67]
The PDF docs build is currently broken.

This can be seen on Readthedocs e.g here:
https://readthedocs.org/projects/probfit/builds/4547493/

Locally, I tried:

```
cd doc
make pdflatex
```

and got a LaTeX error pointing to this line in the generated `probfit.tex`

```
l.219 ...(x, args, \ldots) \textrm{d} x\end{split}
```

which is pointing to the formula in description of the `extended` argument of `UnbinnedLH`.

I wasn't able to identify or fix the issue, so I'm filing this reminder issue.
Someone knowledgeable with Sphinx and LaTeX, please help out!

For now, I've disabled the PDF build on RTD.
I'll add it back if someone manages to fix the issue.

**Comment by cdeil** [comment]
Just to note: after disabling the PDF build, the RTD HTML build now works fine: https://readthedocs.org/projects/probfit/builds/4547613/

**Comment by alexpearce** [comment]
@cdeil — You can re-enable the PDF build on RTD if you like :)

**Comment by cdeil** [comment]
@alexpearce - Can you make a (free) RTD account and mention your username here, please?
I'll give you access so that you can change settings in the future as well.

For now - OK, I'm re-enabling the PDF build.

**Comment by alexpearce** [comment]
Thanks a lot. My RTD account is alexpearce.m

**Comment by cdeil** [comment]
You're now "maintainer" on RTD for `iminuit` and `probfit`, i.e. have access to settings and can re-start docs builds as needed.

**Comment by cdeil** [comment]
I did get some weird errors on RTD, so I "wiped" it:
http://docs.gammapy.org/en/latest/development/howto.html?highlight=wipe#wipe-readthedocs

and changed the settings to use Python 3.

The new build is here:
https://readthedocs.org/projects/probfit/builds/4650170/

Looks like it worked.

@alexpearce - Could you please review the docs
http://probfit.readthedocs.io/en/latest/
and check if the version number is the same one you get locally: "Revision 78650f85"?

**Comment by cdeil** [comment]
There is a PDF:
https://media.readthedocs.org/pdf/probfit/latest/probfit.pdf

It's never very pretty, but @alexpearce - does it look roughly OK to you concerning content?
If yes, close this issue?

**Comment by alexpearce** [comment]
> Could you please review the docs
http://probfit.readthedocs.io/en/latest/
and check if the version number is the same one you get locally: "Revision 78650f8"?

I see "Revision d4a0fb0d" at the bottom of that page. When I `make doc` locally I see "1.0.5" in the header of the sidebar rather than "latest", and no "Revision …" string at the bottom of the page. Strange…

> It's never very pretty

Indeed 😄 But it looks as good as it does locally. It generates the plots in PDF format as well; nice touch 🎨

**Comment by cdeil** [comment]
Concerning the version, it might be something that RTD adds.

Closing this issue now.
If you think version or something else should be improved, please open a new issue.
