### ISSUE TITLE
Remove Cython build files from the repository

### ISSUE THREAD

**Issue by alexpearce** [iminuit/probfit#72]
From [#70 (comment)](https://github.com/iminuit/probfit/pull/70#issuecomment-258766495), we should remove the Cython build files from the repository. This means all `.c`, `.pxd` files, I think.

Developers of probfit can generate the files themselves after doing `pip install cython`. We should add clear instructions for developers in the README.

**Comment by cdeil** [comment]
PXD files aren't auto-generated and shoudn't be removed.
http://cython.readthedocs.io/en/latest/src/tutorial/pxd_files.html

I think it's just the C files that should be removed:
```
$ find . -name '*.c'
./probfit/_libstat.c
./probfit/costfunc.c
./probfit/functor.c
./probfit/funcutil.c
./probfit/pdf.c
```
